#! /bin/bash
sqlpid="/var/run/mysqld/mysqld.pid"
if [ -f "$sqlpid" ]; then
  service mysql stop
  sqlstart=1
fi

touch /var/lib/mysql/ib_logfile0
rm -r /var/lib/mysql/ib_logfile0
touch /var/lib/mysql/ib_logfile1
rm -r /var/lib/mysql/ib_logfile1
touch /var/lib/mysql/ib_logfile2
rm -r /var/lib/mysql/ib_logfile2
mkdir -p /var/lib/.mysql
touch /var/lib/.mysql/ib_logfile0
rm -r /var/lib/.mysql/ib_logfile0
touch /var/lib/.mysql/ib_logfile1
rm -r /var/lib/.mysql/ib_logfile1
touch /var/lib/.mysql/ib_logfile2
rm -r /var/lib/.mysql/ib_logfile2

if [[ $sqlstart -eq 1 ]]; then 
  service mysql start
fi
